export const GET_PRODUCTS = "GET_PRODUCTS";
export const ADD_NEW_PRODUCT = "ADD_NEW_PRODUCT";
export const GET_ONE_PRODUCT = "GET_ONE_PRODUCT";
export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const GET_ERROR = "GET_ERROR";
export const CREATE_MESSAGE = "CREATE_MESSAGE";